### PR TITLE
♻️  Remove unnecessary null checks, which result in compiler warnings.

### PR DESCRIPTION
**Pull request by Phil9l**
According to the Dart flow analysis, the following null-checks are not needed. Removing them to get rid of these compiler warnings.

```
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/cupertino_adaptive_theme.dart:122:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
                   ^

../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/cupertino_adaptive_theme.dart:144:43: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      final brightness = SchedulerBinding.instance!.window.platformBrightness;
                                          ^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/cupertino_adaptive_theme.dart:221:43: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/scheduler/binding.dart').

      final brightness = SchedulerBinding.instance!.window.platformBrightness;
                                          ^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/cupertino_adaptive_theme.dart:231:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);
                   ^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/adaptive_theme.dart:119:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
                   ^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/adaptive_theme.dart:139:43: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      final brightness = SchedulerBinding.instance!.window.platformBrightness;

                                          ^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/adaptive_theme-2.3.1/lib/src/adaptive_theme.dart:218:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);
                   ^
```

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### CODE REVIEW

**Comment by BirjuVachhani** [comment]
@Phil9l I am on Flutter master and I am not able to see this lint warnings. `WidgetsBinding.instance` is null so it needs the null check operator. Also, the tests are failing for the same reason. Are you sure you're on Flutter stable?

**Comment by jeromeDms** [comment]
Hi
I'm facing the same issue using flutter beta channel.
I switched to flutter beta as it largely improve performances on Android apps displaying AdMob ads.
Moving to this beta channel results in WidgetsBinding.instance generating warnings.
Jerome

**Comment by BirjuVachhani** [comment]
I'll try this using beta channel. Maybe a solution would be to release a beta/dev version of the package for flutter beta channel.

**Comment by Livinglist** [comment]
@BirjuVachhani Just tried on Flutter 3.0 with Dart 2.17.0, warnings can be seen now.

**Comment by Livinglist** [comment]
@BirjuVachhani probably because the workflow is using Flutter 2.10.4 instead of 3.0

```
Run actions/checkout@v1
[2](https://github.com/BirjuVachhani/adaptive_theme/runs/6018676980?check_suite_focus=true#step:4:2)
  with:
[3](https://github.com/BirjuVachhani/adaptive_theme/runs/6018676980?check_suite_focus=true#step:4:3)
    clean: true
[4](https://github.com/BirjuVachhani/adaptive_theme/runs/6018676980?check_suite_focus=true#step:4:4)
  env:
[5](https://github.com/BirjuVachhani/adaptive_theme/runs/6018676980?check_suite_focus=true#step:4:5)
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/2.10.4-stable/x[6](https://github.com/BirjuVachhani/adaptive_theme/runs/6018676980?check_suite_focus=true#step:4:6)4
6
    PUB_CACHE: /opt/hostedtoolcache/flutter/2.10.4-stable/x64/.pub-cache
```

**Comment by BirjuVachhani** [comment]
This has been released in [v3.0.0](https://pub.dev/packages/adaptive_theme/versions/3.0.0)

**Pull request merged**
